{{ config(materialized='table') }}

select LOCATION,
sum(TOTAL_ACTIVE_CASES) AS TOTAL_ACTIVE_CASES,
sum(TOTAL_CASES) AS TOTAL_CASES,
sum(TOTAL_DEATHS) AS TOTAL_DEATHS,
sum(TOTAL_RECOVERED) AS TOTAL_RECOVERED,
sum(NEW_ACTIVE_CASES) AS NEW_ACTIVE_CASES,
sum(NEW_CASES) AS  NEW_CASES,
sum(NEW_RECOVERED) AS NEW_RECOVERED,
sum(NEW_DEATHS) AS NEW_DEATHS,
FROM {{source("covid19_data", "ALL_DATA")}}
group by LOCATION;
