{{ config(materialized='table') }}

SELECT DATE(DATE) AS DATE, LOCATION, TOTAL_ACTIVE_CASES AS TOTAL_ACTIVE_CASES,
TOTAL_CASES AS TOTAL_CASES,
TOTAL_DEATHS AS TOTAL_DEATHS,
TOTAL_RECOVERED AS TOTAL_RECOVERED,
NEW_ACTIVE_CASES AS NEW_ACTIVE_CASES,
NEW_CASES AS  NEW_CASES,
NEW_RECOVERED AS NEW_RECOVERED,
NEW_DEATHS AS NEW_DEATHS,
Case_Fatality_Rate AS Case_Fatality_Rate,
Case_Recovered_Rate AS Case_Recovered_Rate
from  {{source("covid19_data", "ALL_DATA")}}
